name: Build and Release Mint bundle

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lua and LuaRocks
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev luarocks pkg-config
          sudo luarocks --lua-version=5.3 install luafilesystem

      - name: Build Mint.min.lua
        run: lua5.3 tools/build_mint.lua

      - name: Publish release asset
        uses: softprops/action-gh-release@v2
        with:
          files: Mint.min.lua
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish raw file to dist branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          mkdir publish
          cp Mint.min.lua publish/
          cd publish
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Mint.min.lua
          git commit -m "Publish Mint.min.lua for ${GITHUB_REF_NAME}"
          git branch -M dist
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push -f origin dist

