name: Build and Release Mint bundle

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lua and LuaRocks
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev luarocks pkg-config
          sudo luarocks --lua-version=5.3 install luafilesystem

      - name: Build Mint.min.lua
        run: lua5.3 tools/build_mint.lua

      - name: Publish release asset
        uses: softprops/action-gh-release@v2
        with:
          files: Mint.min.lua
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

